# Generated by Django 5.2.7 on 2026-01-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
