# Generated by Django 5.2.7 on 2026-01-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0002_alter_candidate_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='resume_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
