# Generated by Django 5.2.7 on 2026-02-03 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_candidate_resume_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, help_text='Question difficulty level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='focus_area',
            field=models.CharField(blank=True, help_text='Area of focus for this question', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='gemini_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Metadata from Gemini generation'),
        ),
        migrations.AddField(
            model_name='question',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 3, 10, 1, 41, 750156, tzinfo=datetime.timezone.utc), help_text='When this question was generated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='is_dynamic',
            field=models.BooleanField(default=True, help_text='Whether this was dynamically generated'),
        ),
    ]
