import React, { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import api from '../api';
import { FileText, MessageSquare, Code, AlertTriangle } from 'lucide-react';

const CandidateDetail = () => {
    const { id } = useParams();
    const [data, setData] = useState(null);

    useEffect(() => {
        fetchDetail();
    }, []);

    const fetchDetail = async () => {
        try {
            const response = await api.get(`/candidates/${id}/detail/`);
            setData(response.data);
        } catch (err) {
            console.error(err);
        }
    };

    if (!data) return <div className="text-center py-20">Loading candidate details...</div>;

    return (
        <div className="max-w-5xl mx-auto space-y-6">
            <div className="bg-white p-6 rounded-lg shadow-sm border border-gray-100 flex justify-between items-end">
                <div>
                    <h1 className="text-2xl font-bold">{data.name}</h1>
                    <p className="text-gray-500">{data.email}</p>
                </div>
                {data.evaluation && (
                    <div className="text-right">
                        <div className="text-3xl font-bold text-indigo-600">{data.evaluation.overall_score}%</div>
                        <div className="text-xs text-gray-400 uppercase tracking-wider">Overall Score</div>
                    </div>
                )}
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <div className="lg:col-span-2 space-y-6">
                    {/* Questions & Answers */}
                    <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
                        <div className="p-4 bg-gray-50 border-b font-bold flex items-center">
                            <MessageSquare className="w-5 h-5 mr-2 text-indigo-600" /> Interview Session (Questions Generated by Gemini)
                        </div>
                        <div className="p-4 space-y-6">
                            {data.questions.map((q, idx) => (
                                <div key={q.id} className="border-b pb-4 last:border-0">
                                    <div className="flex justify-between">
                                        <span className="text-xs font-bold text-gray-400 uppercase">Question {idx + 1} ({q.question_type})</span>
                                        <span className="text-xs text-gray-400">{q.time_limit}s/m limit</span>
                                    </div>
                                    <p className="font-medium mt-1">{q.text}</p>
                                    <div className="mt-3 bg-gray-50 p-3 rounded text-sm text-gray-600 italic">
                                        Candidate Response: {q.answers && q.answers.length > 0 ? (
                                            q.answers[0].response_text || (q.answers[0].response_file ? "Audio/Video Recording Uploaded" : "No text/file response")
                                        ) : "No response yet"}
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* AI Evaluation Summary */}
                    {data.evaluation && (
                        <div className="bg-indigo-50 rounded-lg p-6 border border-indigo-100">
                            <h2 className="font-bold text-indigo-900 mb-2">Gemini AI Evaluation Summary</h2>
                            <p className="text-indigo-800 text-sm leading-relaxed">{data.evaluation.summary}</p>
                        </div>
                    )}
                </div>

                <div className="space-y-6">
                    {/* Resume Parsed Text */}
                    <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
                        <div className="p-4 bg-gray-50 border-b font-bold flex items-center">
                            <FileText className="w-5 h-5 mr-2 text-indigo-600" /> Parsed Resume Content
                        </div>
                        <div className="p-4 h-64 overflow-y-auto text-xs text-gray-600 whitespace-pre-wrap">
                            {data.resume_text}
                        </div>
                    </div>

                    {/* Cheating Indicators */}
                    <div className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden">
                        <div className="p-4 bg-gray-50 border-b font-bold flex items-center">
                            <AlertTriangle className="w-5 h-5 mr-2 text-red-600" /> Cheating Indicators
                        </div>
                        <div className="p-4 space-y-3">
                            {data.cheating_logs.map((log) => (
                                <div key={log.id} className="flex items-start text-xs border-l-2 border-red-500 pl-3 py-1">
                                    <div>
                                        <div className="font-bold text-red-700">{log.event_type}</div>
                                        <div className="text-gray-500">{new Date(log.timestamp).toLocaleTimeString()}</div>
                                    </div>
                                </div>
                            ))}
                            {data.cheating_logs.length === 0 && (
                                <p className="text-xs text-green-600 font-medium text-center py-4">No suspicious activity detected.</p>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default CandidateDetail;
